filebeat.inputs:
  - type: log
    id: sample-logs
    enabled: true
    paths:
      - /sample-logs/*.log
    fields:
      source_type: "sample"
    fields_under_root: true

processors:
  - add_host_metadata: ~
  - add_cloud_metadata: ~
  - add_docker_metadata: ~
  - decode_json_fields:
      fields: ["message"]
      target: "json"
      overwrite_keys: true
      add_error_key: true
      when:
        contains:
          message: "{"
# ^ decode_json_fields is harmless for plain text; useful if your lines are JSON.

output.logstash:
  hosts: ["logstash:5044"]

setup.template.enabled: false
setup.ilm.enabled: false
logging.to_files: false
