apiVersion: sparkoperator.k8s.io/v1beta2
kind: SparkApplication
metadata:
  name: auto-train-pipeline
  namespace: ml-pipelines
spec:
  type: Python
  mode: cluster
  sparkVersion: "3.5.1"
  image: spark:python3
  imagePullPolicy: IfNotPresent

  mainApplicationFile: local:///opt/spark/work-dir/train_pipeline.py

  deps:
    packages:
      - org.apache.hadoop:hadoop-aws:3.3.4
      - com.amazonaws:aws-java-sdk-bundle:1.12.262

  sparkConf:
    "spark.hadoop.fs.s3a.impl": "org.apache.hadoop.fs.s3a.S3AFileSystem"
    "spark.hadoop.fs.s3a.aws.credentials.provider": "com.amazonaws.auth.DefaultAWSCredentialsProviderChain"
    "spark.jars.ivy": "/tmp/.ivy2"

  restartPolicy:
    type: Always

  volumes:
    - name: app-script
      configMap:
        name: auto-train-script

  driver:
    cores: 1
    memory: "2g"
    serviceAccount: spark
    volumeMounts:
      - name: app-script
        mountPath: /opt/spark/work-dir/train_pipeline.py   # <-- mount a FILE, not the dir
        subPath: train_pipeline.py                         # <-- key inside ConfigMap

  executor:
    instances: 2
    cores: 1
    memory: "2g"
    volumeMounts:
      - name: app-script
        mountPath: /opt/spark/work-dir/train_pipeline.py
        subPath: train_pipeline.py