apiVersion: apps/v1
kind: Deployment
metadata:
  name: spark-notebook
  namespace: spark-nb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spark-notebook
  template:
    metadata:
      labels:
        app: spark-notebook
    spec:
      containers:
        - name: notebook
          image: jupyter/pyspark-notebook:latest
          args:
            - start-notebook.sh
            - "--NotebookApp.token=''"
            - "--NotebookApp.password=''"
          ports:
            - containerPort: 8888
          resources:
            requests:
              cpu: "200m"
              memory: "512Mi"
            limits:
              cpu: "500m"
              memory: "768Mi"
          env:
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: spark-aws-creds
                  key: AWS_ACCESS_KEY_ID
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: spark-aws-creds
                  key: AWS_SECRET_ACCESS_KEY
            - name: AWS_REGION
              valueFrom:
                secretKeyRef:
                  name: spark-aws-creds
                  key: AWS_REGION
