apiVersion: apps/v1
kind: Deployment
metadata:
  name: spark-notebook
  namespace: spark-nb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spark-notebook
  template:
    metadata:
      labels:
        app: spark-notebook
    spec:
      containers:
        - name: notebook
          image: jupyter/pyspark-notebook:latest
          args:
            - start-notebook.sh
            - "--NotebookApp.token=''"
            - "--NotebookApp.password=''"
          ports:
            - containerPort: 8888

---
apiVersion: v1
kind: Service
metadata:
  name: spark-notebook
  namespace: spark-nb
spec:
  type: ClusterIP
  selector:
    app: spark-notebook
  ports:
    - name: http
      port: 8888
      targetPort: 8888

