apiVersion: ray.io/v1
kind: RayJob
metadata:
  name: log-train-job
  namespace: ray
spec:
  clusterSelector:
    ray.io/cluster: ray-cluster
  entrypoint: "python /app/train.py"
  shutdownAfterJobFinishes: true
  runtimeEnvYAML: |
    pip:
      - pandas
      - pyarrow
      - s3fs
      - numpy
      - torch
      - transformers
      - datasets
      - accelerate
      - evaluate
      - scikit-learn==1.3.2
      - peft