apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kuberay-operator
  namespace: ray-system
spec:
  interval: 15m
  releaseName: kuberay-operator
  chart:
    spec:
      chart: kuberay-operator
      sourceRef:
        kind: HelmRepository
        name: kuberay
        namespace: flux-system
      interval: 30m

  install:
    createNamespace: true
    remediation:
      retries: 3

  upgrade:
    remediation:
      retries: 3

  values:
    # safe defaults; operator creates CRDs + controllers
    image:
      repository: rayproject/kuberay-operator