apiVersion: ray.io/v1
kind: RayCluster
metadata:
  name: ray-cluster
  namespace: ray
  labels:
    ray.io/cluster: ray-cluster
spec:
  rayVersion: "2.9.3"
  headGroupSpec:
    rayStartParams:
      dashboard-host: "0.0.0.0"
    template:
      spec:
        containers:
          - name: ray-head
            image: rayproject/ray:2.9.3-py310
            env:
              - name: DATA_PATH
                value: "s3://mas-pipeline-prod/processed/your_dataset/"
              - name: AWS_DEFAULT_REGION
                value: "us-west-2"
            ports:
              - containerPort: 6379
                name: gcs
              - containerPort: 8265
                name: dashboard
              - containerPort: 10001
                name: client
            resources:
              requests:
                cpu: "2"
                memory: "4Gi"
              limits:
                cpu: "2"
                memory: "4Gi"

  workerGroupSpecs:
    - groupName: cpu-workers
      replicas: 2
      minReplicas: 0
      maxReplicas: 10
      rayStartParams: {}
      template:
        spec:
          containers:
            - name: ray-worker
              image: rayproject/ray:2.9.3-py310
              env:
                - name: DATA_PATH
                  value: "s3://mas-pipeline-prod/processed/your_dataset/"
                - name: AWS_DEFAULT_REGION
                  value: "us-west-2"
              resources:
                requests:
                  cpu: "4"
                  memory: "8Gi"
                limits:
                  cpu: "4"
                  memory: "8Gi"