apiVersion: ray.io/v1
kind: RayJob
metadata:
  name: log-train-job
  namespace: ray
spec:
  # IMPORTANT: selector is a STRING in your CRD version
  clusterSelector: 'ray.io/cluster=ray-cluster'

  entrypoint: "python /app/train_ray.py"
  shutdownAfterJobFinishes: true

  runtimeEnvYAML: |
    pip:
      - pandas
      - pyarrow
      - s3fs
      - scikit-learn
      - joblib