apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: spark-operator
  namespace: flux-system
spec:
  interval: 1h
  url: https://kubeflow.github.io/spark-operator
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: kuberay
  namespace: flux-system
spec:
  interval: 30m
  url: https://ray-project.github.io/kuberay-helm/
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: autoscaler
  namespace: flux-system
spec:
  interval: 30m
  url: https://kubernetes.github.io/autoscaler
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: strimzi
  namespace: flux-system
spec:
  interval: 10m
  url: https://strimzi.io/charts/
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: elastic
  namespace: flux-system
spec:
  interval: 30m
  url: https://helm.elastic.co
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: prometheus-community
  namespace: flux-system
spec:
  interval: 10m
  url: https://prometheus-community.github.io/helm-charts
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: bitnami-mongodb
  namespace: flux-system
spec:
  interval: 1h
  url: oci://registry-1.docker.io/bitnamicharts/mongodb
  ref:
    tag: 16.5.45