apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: spark-operator
  namespace: flux-system
spec:
  interval: 1h
  url: https://kubeflow.github.io/spark-operator
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: kuberay
  namespace: flux-system
spec:
  interval: 30m
  url: https://ray-project.github.io/kuberay-helm/