apiVersion: apps/v1
kind: Deployment
metadata:
  name: nexus-trace-analyzer
  namespace: nexus-trace
  labels:
    app.kubernetes.io/name: nexus-trace-analyzer
    app.kubernetes.io/component: inference
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: nexus-trace-analyzer
  template:
    metadata:
      labels:
        app.kubernetes.io/name: nexus-trace-analyzer
        app.kubernetes.io/component: inference
    spec:
      containers:
        - name: analyzer
          image: chelseajaculina/lsa-analyzer:1.0.2
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8000
          env:
          - name: MODEL_TIMEOUT_S
            value: "300"

          - name: RCA_QWEN_URL
            value: "http://rca-qwen.nexus-trace.svc.cluster.local:8000"

          - name: RCA_QWEN_MODEL
            value: "rca-qwen"

          - name: RCA_DEEPSEEK_URL
            value: "http://rca-deepseek.nexus-trace.svc.cluster.local:8000"

          - name: RCA_DEEPSEEK_MODEL
            value: "rca-deepseek"

          - name: EXECUTOR_URL
            value: "http://rca-qwen.nexus-trace.svc.cluster.local:8000"

          - name: EXECUTOR_MODEL
            value: "rca-qwen"

          - name: VALIDATOR_URL
            value: "http://rca-qwen.nexus-trace.svc.cluster.local:8000"

          - name: VALIDATOR_MODEL
            value: "rca-qwen"

          - name: RCA_LANGGRAPH_URL
            value: "http://rca-agent.nexus-trace.svc.cluster.local:8080"

          readinessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 15
            periodSeconds: 20
          resources:
            requests:
              cpu: "250m"
              memory: "512Mi"
            limits:
              cpu: "2"
              memory: "4Gi"

---
apiVersion: v1
kind: Service
metadata:
  name: analyzer
  namespace: nexus-trace
  labels:
    app.kubernetes.io/name: nexus-trace-analyzer
    app.kubernetes.io/component: inference
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: nexus-trace-analyzer
  ports:
    - name: http
      port: 8000
      targetPort: http
