apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: namespaces
  namespace: flux-system
spec:
  interval: 1m
  prune: true
  sourceRef:
    kind: GitRepository
    name: app-source
    namespace: flux-system
  path: ./clusters/elk/namespace
  wait: true
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: flux-controllers
  namespace: flux-system
spec:
  interval: 1m
  prune: true
  dependsOn:
    - name: namespaces
  sourceRef:
    kind: GitRepository
    name: app-source
    namespace: flux-system
  path: ./clusters/elk/flux-system
  wait: true
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: elastic-stack
  namespace: flux-system
spec:
  interval: 1m
  prune: true
  dependsOn:
    - name: flux-controllers
  sourceRef:
    kind: GitRepository
    name: app-source
    namespace: flux-system
  path: ./clusters/elk/elastic
  wait: true
