apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: app-source
  namespace: flux-system
spec:
  interval: 1m
  url: https://github.com/Najel-A/Multi-Agent-Collaboration-System
  ref:
    branch: najel-dev
