apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: litellm
  namespace: nexus-trace
spec:
  interval: 5m
  chart:
    spec:
      chart: litellm-helm
      version: "1.81.14-stable"
      sourceRef:
        kind: HelmRepository
        name: litellm
        namespace: flux-system

  values:
    replicaCount: 1

    image:
      repository: ghcr.io/berriai/litellm-database
      tag: "main-v1.81.14-stable"
      pullPolicy: IfNotPresent

    service:
      type: ClusterIP
      port: 4000

    masterkey: "sk-change-this-master-key"

    db:
      useExisting: false
      deployStandalone: true

    postgresql:
      architecture: standalone
      auth:
        username: litellm
        database: litellm
        password: "change-this-db-password"
        postgres-password: "change-this-postgres-password"

    proxy_config:
      model_list:
        - model_name: llama3.2:3b
          litellm_params:
            model: ollama/llama3.2:3b
            api_base: http://ollama-2b.nexus-trace.svc.cluster.local:11434

        - model_name: rca-deepseek
          litellm_params:
            model: openai/rca-deepseek
            api_base: http://rca-deepseek.nexus-trace.svc.cluster.local:8000/v1
            api_key: dummy

      mcp_servers:
        k8s_mcp_readonly:
          url: http://k8s-mcp-readonly.nexus-trace.svc.cluster.local:8080/mcp
          transport: http

    general_settings:
      master_key: os.environ/PROXY_MASTER_KEY

    resources:
      requests:
        cpu: 250m
        memory: 512Mi
      limits:
        cpu: "1"
        memory: 1Gi