apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: spark-operator
  namespace: spark-operator
spec:
  interval: 10m
  chart:
    spec:
      chart: spark-operator
      version: ">=2.0.0 <3.0.0"
      sourceRef:
        kind: HelmRepository
        name: spark-operator
        namespace: flux-system

  install:
    crds: CreateReplace
  upgrade:
    crds: CreateReplace

  values:
    # Optional but recommended
    webhook:
      enable: true
    metrics:
      enable: true
    controller:
      jobNamespacesnamespaces:
      - ml-pipelines
    
