apiVersion: v1
kind: ServiceAccount
metadata:
  name: spark
  namespace: dp-clean
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: spark-driver-role
  namespace: dp-clean
rules:
  - apiGroups: [""]
    resources:
      - pods
      - pods/log
      - services
      - configmaps
      - events
      - persistentvolumeclaims
    verbs:
      - get
      - list
      - watch
      - create
      - delete
      - deletecollection
      - patch
      - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: spark-driver-rb
  namespace: dp-clean
subjects:
  - kind: ServiceAccount
    name: spark
    namespace: dp-clean
roleRef:
  kind: Role
  name: spark-driver-role
  apiGroup: rbac.authorization.k8s.io