apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: elasticsearch-sample
  namespace: elastic-system
spec:
  version: 8.14.0
  nodeSets:
    - name: default
      count: 1
      config:
        node.store.allow_mmap: false
      # 👇 This line is critical: disable default PVCs
      volumeClaimTemplates: []
      podTemplate:
        spec:
          containers:
            - name: elasticsearch
              resources:
                requests:
                  cpu: "500m"
                  memory: "1Gi"
                limits:
                  cpu: "1"
                  memory: "1Gi"
              env:
                - name: ES_JAVA_OPTS
                  value: "-Xms512m -Xmx512m"
