apiVersion: beat.k8s.elastic.co/v1beta1
kind: Beat
metadata:
  name: filebeat-sample
  namespace: elastic-system
spec:
  type: filebeat
  version: 8.14.0

  daemonSet:
    podTemplate:
      spec:
        containers:
          - name: filebeat
            securityContext:
              runAsUser: 0
            volumeMounts:
              - name: varlog
                mountPath: /var/log
              - name: varlibdockercontainers
                mountPath: /var/lib/docker/containers
                readOnly: true
        volumes:
          - name: varlog
            hostPath:
              path: /var/log
          - name: varlibdockercontainers
            hostPath:
              path: /var/lib/docker/containers

  config:
    filebeat.inputs:
      # Read the merged/enriched CSV file
      - type: filestream
        id: spark_csv
        enabled: true
        paths:
          - /var/log/spark/Spark_logs_enriched.csv
        # optional: stop after reaching EOF (good for batch files)
        close_eof: true

    # Route to Logstash
    output.logstash:
      hosts: ["logstash-sample-ls-beats.elastic-system.svc:5044"]
