apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: elasticsearch-sample
  namespace: elastic-system
spec:
  version: 8.14.0
  nodeSets:
    - name: default
      count: 1
      config:
        node.store.allow_mmap: false
      podTemplate:
        spec:
          nodeSelector:
            kubernetes.io/arch: arm64 # <-- Najel's hotfix for M-series CPUs, remove if not needed
