apiVersion: beat.k8s.elastic.co/v1beta1
kind: Beat
metadata:
  name: filebeat-sample
  namespace: elastic-system
spec:
  type: filebeat
  version: 8.14.0
  elasticsearchRef:
    name: elasticsearch-sample
  kibanaRef:
    name: kibana-sample
  daemonSet:
    podTemplate:
      spec:
        containers:
          - name: filebeat
            securityContext:
              runAsUser: 0
  config:
    filebeat.inputs:
      - type: container
        paths:
          - /var/log/containers/*.log
        processors:
          - add_kubernetes_metadata: {}
    output.elasticsearch:
      hosts: ["https://elasticsearch-sample-es-http.elastic-system.svc:9200"]
      username: elastic
      password: ${ELASTIC_PASSWORD}
      ssl:
        verification_mode: none
