apiVersion: beat.k8s.elastic.co/v1beta1
kind: Beat
metadata:
  name: filebeat-sample
  namespace: elastic-system
spec:
  type: filebeat
  version: 8.14.0
  # You can keep kibanaRef only if you plan to use setup.kibana/dashboard loading.
  # kibanaRef:
  #   name: kibana-sample

  daemonSet:
    podTemplate:
      spec:
        containers:
          - name: filebeat
            securityContext:
              runAsUser: 0
            volumeMounts:
              - name: varlog
                mountPath: /var/log
              - name: varlibdockercontainers
                mountPath: /var/lib/docker/containers
                readOnly: true
        volumes:
          - name: varlog
            hostPath:
              path: /var/log
          - name: varlibdockercontainers
            hostPath:
              path: /var/lib/docker/containers

  config:
    filebeat.inputs:
      - type: container
        paths:
          - /var/log/containers/*.log
        processors:
          - add_kubernetes_metadata: {}

    # Route to Logstash (no ES creds needed)
    output.logstash:
      hosts: ["logstash-sample-ls-beats.elastic-system.svc:5044"]
      # If you enabled TLS on the beats input, add ssl settings here:
      # ssl:
      #   certificate_authorities: ["/mnt/ca/ca.crt"]
