apiVersion: logstash.k8s.elastic.co/v1alpha1
kind: Logstash
metadata:
  name: logstash-sample
  namespace: elastic-system
spec:
  version: 8.14.0
  count: 1
  elasticsearchRefs:
    - name: elasticsearch-sample
      namespace: elastic-system

  # NEW: load the wrapper secret into the keystore
  secureSettings:
    - secretName: elastic-credentials

  pipelines:
    - pipeline.id: main
      config.string: |
        input { beats { port => 5044 } }
        output {
          elasticsearch {
            hosts => ["https://elasticsearch-sample-es-http.elastic-system.svc:9200"]
            user  => "elastic"
            password => "${ELASTIC_PASSWORD}"
            ssl   => true
            ssl_certificate_verification => false
          }
        }

  services:
    - name: beats
      service:
        spec:
          type: ClusterIP
          ports:
            - name: beats
              port: 5044
              targetPort: 5044
